#:schema node_modules/wrangler/config-schema.json
name = "v2ray-sub2json"
main = "src/_worker.js"
compatibility_date = "2025-03-20"
workers_dev = true
[build]
format = "service-worker" # Explicitly set Service Worker format



