name: Deploy Worker

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.0'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # Build the project
      - name: Build
        run: npm run build  # Generates .svelte-kit/cloudflare/_worker.js

      # Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy